[[redirects]]
    from = "/auth/admin"
    to = "https://charme-api-vercel.vercel.app/api/v1/auth/admin"
    status = 200
    force = true
    header = {X-From = "Netlify"}


[[redirects]]
    from = "/user"
    to = "https://charme-api-vercel.vercel.app/api/v1/user"
    status = 200
    force = true
    header = {X-From = "Netlify"}

[[redirects]]
    from = "/time"
    to = "https://charme-api-vercel.vercel.app/api/v1/time"
    status = 200
    force = true
    header = {X-From = "Netlify"}

[[redirects]]
    from = "/order"
    to = "https://charme-api-vercel.vercel.app/api/v1/order"
    status = 200
    force = true
    header = {X-From = "Netlify"}

[[redirects]]
    from = "/order/date/*"
    to = "https://charme-api-vercel.vercel.app/api/v1/order/date/:splat"
    status = 200
    force = true
    header = {X-From = "Netlify"}


